services:
  minecraft:
    build: .
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: "1.21.4"
      MEMORY: "2G"
    ports:
      - "25565:25565"
      - "127.0.0.1:2222:2222"
    volumes:
      - ./data:/data
